# Generated by Django 2.0.1 on 2018-03-01 13:58

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180228_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='support_staff',
            field=models.CharField(default=uuid.uuid4, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 1, 13, 58, 24, 473391)),
        ),
    ]
