# Generated by Django 2.0.1 on 2018-03-01 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180301_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='support_staff',
            new_name='user_code',
        ),
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 1, 15, 50, 48, 647035)),
        ),
    ]
