# Generated by Django 2.0.1 on 2018-03-02 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180301_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
