# Generated by Django 2.0.1 on 2018-03-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180302_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='is_only_auth',
            field=models.BooleanField(default=False),
        ),
    ]
