# Generated by Django 2.0.1 on 2018-03-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180317_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='browser',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='country',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
