# Generated by Django 2.0.1 on 2018-03-18 16:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180317_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 18, 16, 25, 47, 771243, tzinfo=utc)),
        ),
    ]
