# Generated by Django 2.0.1 on 2018-03-22 16:43

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_profile_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='api_key1',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='api_key2',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
    ]
